### PR TITLE
Update psi_hu.ts

### PR DESCRIPTION
**Pull request by Sanyy**

### CODE REVIEW

**Comment by Sanyy** [comment]
Hy, is there anyone who can tell me:
- Am i doing this right because i am a newbie on github? I'm a bit confused which 'branch' should or should not be bothered.
- After i saw some blatant grammar mistakes in the program, i decided to help you if i can and if you let me.

Psi+ is great software this is the least what i can do to help others using it.

Any answer appreciated.

**Comment by tehnick** [comment]
Hi,

Could you use transifex.com for uploading translations as other our translators?

**Comment by Sanyy** [comment]
Never heard from it. But looks much more easier than rolling the pages.
- There is a 15 days/mail trial should be enough to learn its functions.
I registered as sanyy do i have to join to the team?

**Comment by tehnick** [comment]
> There is a 15 days/mail trial should be enough to learn its functions.

Please use permanent email address even if you want to stay anonymous. It is used for notifications about translation updates and/or new messages from other Transifex users.

> I registered as sanyy do i have to join to the team?

I added you to Hungarian language team. Have fun.

**Pull request closed without merging**
