### PR TITLE
I translated and fixed ~30% Vietnamese translation

### PR DESCRIPTION
**Pull request by saphire7**
I translated and fixed ~30% Vietnamese translation

### CODE REVIEW

**Comment by tehnick** [comment]
Thanks!

**Comment by tehnick** [comment]
@saphire7 
Transifex shows what about 66.5% of file is translated now:
https://www.transifex.com/tehnick/psi-plus/language/vi/
(This already after your update.)

**Comment by tehnick** [comment]
@saphire7
Would you like to be mentioned in [AUTHORS](https://github.com/psi-plus/psi-plus-l10n/blob/master/AUTHORS#L125) file?

**Comment by saphire7** [comment]
> @saphire7
> Would you like to be mentioned in [AUTHORS](https://github.com/psi-plus/psi-plus-l10n/blob/master/AUTHORS#L125) file?

Yes please, i updated in [AUTHORS](https://github.com/psi-plus/psi-plus-l10n/blob/master/AUTHORS#L125) file. Thanks.

**Comment by saphire7** [comment]
> Thanks!

You're welcome. I have just joined contributor community so I am learning how to use Git to contribute Vietnamese localize. Hope receives any support from you and colleague. Thank you!

**Pull request merged**
