### PR TITLE
update japanese translations

### PR DESCRIPTION
**Pull request by hamano**
Hi,
I am PSI japanese translator.
Also the psi_ja.ts of psi plus is witten by me but too old.
Please update message the following procedures.
1. update from my psi translation(this PL)
2. please execute update-repo.sh
3. I'll translate remains

Thank you.

### CODE REVIEW

**Comment by tehnick** [comment]
Hi. Why do not you use the Transifex service as described in README?

**Comment by hamano** [comment]
Historically, psi plus' psi_ja.ts come from psi's stuff. doesn’t it?
http://psi-im.org/download/lang/ja
After that, I have improved many translation to psi's psi_ja.ts.(ex: Jabber -> XMPP)
It is hard to repeat these modifications to psi plus translation using transifex.
Please just overwrite the newest psi_ja.ts. 
I'll complete 100% translation coverage.

**Comment by tehnick** [comment]
> Historically, psi plus' psi_ja.ts come from psi's stuff. doesn’t it?

Not all of them.

> It is hard to repeat these modifications to psi plus translation using transifex.

There is no need to do extra manual work at Transifex. You may just upload your file there and Transifex will update translation for the coincident strings.

**Comment by hamano** [comment]
I didn't know that.
OK, I've just request to join to transifex team.
Thank you.

**Pull request closed without merging**
